# Generated by Django 3.2 on 2021-04-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Owner_info', models.CharField(max_length=100)),
                ('Employee_size', models.IntegerField()),
            ],
        ),
    ]
